### PR TITLE
Magic123

### PR DESCRIPTION
**Pull request by bennyguo**
Magic123 coarse stage implementation with the new unified zero123 and SD guidance.

### CODE REVIEW

**Comment by bennyguo** [comment]
catstatue_rgba

https://github.com/threestudio-project/threestudio/assets/19284678/bf9f6772-93ae-4385-b6b1-46ccd662068f

dog1

https://github.com/threestudio-project/threestudio/assets/19284678/a721eb06-a64b-4040-b7d3-14522e6ee26d

grootplant_rgba

https://github.com/threestudio-project/threestudio/assets/19284678/9ac0d4b1-9015-41d0-ba0f-f8c9674177b4

**Review by MrTornado24 — APPROVED** [review]

**Comment by yankeesong** [comment]
Great work! I tried this simple prompt:

```python launch.py --config configs/magic123.yaml --train --gpu 0 data.image_path=/path/to/dragon_rgba.png system.renderer.num_samples_per_ray=256 data.width=64 data.height=64```

but got the following error:

```
MissingMandatoryValue: Missing mandatory value: tag
    full_key: tag
    object_type=dict
```

Do you have an idea how to resolve this? Thanks!

**Comment by bennyguo** [comment]
@yankeesong you also need to specify `system.prompt_processor.prompt`

**Comment by yankeesong** [comment]
Oh got it. So currently textual inversion is not supported right?

**Comment by bennyguo** [comment]
Yes and I don't plan to support it :)

**Comment by ajhamdi** [comment]
Thanks for integrating our Magic123 into threestudio !

**Pull request merged**
