### PR TITLE
Adds stable-zero123 guidance

### PR DESCRIPTION
**Pull request by voletiv**
Adds guidance for Stable-Zero123 model. Doesn't affect anything else!

Final_video_v01

### CODE REVIEW

**Comment by bennyguo** [comment]
Looks good to me (although can't be tested). @DSaurus

**Comment by DSaurus** [comment]
Looks good to me. I've also made modifications to the config and misc code for more general use cases. Please review it before merging. @voletiv

**Review by DSaurus — APPROVED** [review]

**Comment by voletiv** [comment]
@DSaurus Done! Lgtm :)

**Comment by voletiv** [comment]
@DSaurus @bennyguo I changed the link to the HF repo, please review again :)

**Review by aletts — APPROVED** [review]

**Review by DSaurus — APPROVED** [review]
Okay, lgtm!

**Pull request merged**
