### PR TITLE
HiFA and prolificdreamer+HiFA

### PR DESCRIPTION
**Pull request by JunzheJosephZhu**
Fixed z-variance loss by normalizing weights. This is crucial to ensure that the model isn't encourage to generate empty pixels(since empty pixels have zero z-variance)

Added other HiFA(image space loss, annealing) changes to stable-diffusion-vsd-guidance, and created 2 corresponding configs(for prolificdreamer and prolificdreamer-scene). All changes are option based and do not change normal behavior if use_img_loss and sqrt_annealing are both set to false in config.  I had to pass the value of trainer's max_steps to system.guidance in launch script, since this is the only way to do annealing based on global steps.

Added HiFA config which is based on dreamfusion-sd. I made minor changes to dreamfusion-sd to look out for z-variance loss, and changed stable-diffusion-guidance similar to how i changed stable-diffusion-vsd-guidance. 

Will do another pull request soon to update readme and link to my official repo(which was recently released). I'm still running experiments to search for the best z-variance hyperparameter in threestudio, will update that later too in that PR.

### CODE REVIEW

**Comment by bennyguo** [comment]
Hi Joseph, thank you for the contribution! I saw you're using stable-diffusion-guidance instead of stable-diffusion-unified-guidance for the HiFA implementation, where the latter provides useful options like return_rgb_1step_orig and return_rgb_multistep_orig which can make HiFA implementation much easier and keep a clean code structure. Could you please take a look?

**Comment by JunzheJosephZhu** [comment]
sounds good, will take a look asap. One question: I only see this guidance used in magic123 and experimental/dreamfusion-sd. Isn't this going to make the changes I propose harder to adapt to existing systems since the guidance needs to be switched?

**Comment by bennyguo** [comment]
@JunzheJosephZhu Sorry for the inconvenience. stable-diffusion-unified-guidance covers all the functionality of stable-diffusion-guidance and ideally should be used in all systems. Feel free to use it in HiFA system and I'll switch the guidance in other systems to the unified guidance soon.

**Comment by HiFA-team** [comment]
sounds good. all my code has been pushed. Could you go review the commit and approve it please?

**Comment by JunzheJosephZhu** [comment]
Sounds good. All my code has been pushed. Could you go through the commit and approve it please?

**Review by DSaurus — CHANGES_REQUESTED** [review]
Thank you for your work and effort! However, I noticed that there are many modifications in this commit, some of which may not be necessary. We aim to keep the original system unchanged to ensure rigorous academic comparison with the original method. If there are new systems like HIFA, it would be better to create new configurations and systems rather than modifying the existing ones. In addition, modifications to the guidance should ideally be integrated into the unified guidance. 

 I think the most important thing is to maintain the consistency and clarity of our codebase. I appreciate your understanding and look forward to your next commit.

**Comment by JunzheJosephZhu** [comment]
Could we have a quick call? My wechat is 17717613901, would like to clarify
a few implementation details

**Comment by DSaurus** [comment]
Hi @JunzheJosephZhu ,

I have invited you to join threestudio project. It would be better if you could create a branch and submit a new pull request.

**Pull request closed without merging**
