### PR TITLE
Zero123: Updates to README

### PR DESCRIPTION
**Pull request by voletiv**
Updates README file with examples from Zero123 implementation, edits the files to replace Zero123 with Zero123XL

### CODE REVIEW

**Comment by bennyguo** [comment]
Great work @voletiv ! Will merge this after other related PRs are resolved.

**Comment by voletiv** [comment]
@bennyguo Can this be merged now?

**Review by bennyguo — APPROVED** [review]

**Comment by bennyguo** [comment]
Sure, if other related PRs are already merged. BTW, could the provided example command reproduce the results in the video?

**Comment by voletiv** [comment]
I've uploaded `dog1_rgba.png`, so it should give the correct result for it. I haven't uploaded any of the other images, but they should work with the same command

**Pull request merged**
